// ESLint flat config — extends the rules generated by @nuxt/eslint
// (.nuxt/eslint.config.mjs is produced by `nuxt prepare`).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Single-word page/layout names are fine for this app.
    'vue/multi-word-component-names': 'off',
  },
})
